"use client";

import { motion } from "framer-motion";
import {
  CpuChipIcon,
  ExclamationTriangleIcon,
  ShieldCheckIcon,
  SparklesIcon,
} from "@heroicons/react/24/outline";
import type { GroundedAnswer, ResearchResponse } from "@/lib/types";

interface AnswerHeroProps {
  result: ResearchResponse;
}

/** Big "answer" card at the top of the result section. */
export function AnswerHero({ result }: AnswerHeroProps) {
  const answer = result.answer ?? null;
  const decision = result.output.decision;
  // Prefer the generated grounded answer; fall back to the deterministic
  // synthesis paragraph if generation was unavailable.
  const fallbackSynthesis =
    decision?.synthesis ?? "Pipeline completed but produced no synthesis.";
  const showFallback = !answer || !answer.generated || !answer.text;
  const answerText = showFallback ? fallbackSynthesis : answer!.text;

  const adapter = (result.adapter_metadata?.["sft_adapter"] as string | undefined) ??
                  (result.adapter_metadata?.["adapter_path"] as string | undefined) ??
                  "v3";
  const adapterShort = adapter.split("/").pop() ?? adapter;

  return (
    <motion.section
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.55 }}
      className="surface-panel relative overflow-hidden rounded-3xl p-6 md:p-9"
    >
      {/* Hero accent */}
      <div className="pointer-events-none absolute inset-0 bg-hero-gradient opacity-90" />
      <div className="pointer-events-none absolute -top-24 left-1/2 h-48 w-[40rem] -translate-x-1/2 rounded-full bg-brand-500/30 blur-3xl" />
      <div className="pointer-events-none absolute inset-0 rounded-3xl ring-1 ring-inset ring-white/[0.06]" />

      <div className="relative flex items-start justify-between gap-6">
        <div className="min-w-0 flex-1">
          <div className="mb-2 text-[11px] font-semibold uppercase tracking-[0.18em] text-brand-300">
            Question
          </div>
          <h2 className="text-xl font-semibold leading-snug text-ink-50 md:text-2xl">
            {result.goal}
          </h2>

          <div className="mt-5 flex items-center gap-2">
            <div className="text-[11px] font-semibold uppercase tracking-[0.18em] text-brand-300">
              Answer
            </div>
            {answer?.generated ? (
              <span
                title="Generated by the base Qwen-0.5B-Instruct model (the v3 LoRA adapter is bypassed for free-form prose and used only as a pairwise claim judge)."
                className="inline-flex items-center gap-1 rounded-full border border-brand-400/30 bg-brand-500/10 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider text-brand-200"
              >
                <SparklesIcon className="h-3 w-3" />
                generated locally
              </span>
            ) : (
              <span className="inline-flex items-center gap-1 rounded-full border border-accent-amber/30 bg-accent-amber/10 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider text-accent-amber">
                <ExclamationTriangleIcon className="h-3 w-3" />
                fallback
              </span>
            )}
          </div>

          <p className="mt-2 text-base leading-relaxed text-ink-100 md:text-[17px] md:leading-[1.7]">
            <AnswerText text={answerText} />
          </p>

          {answer?.generated && answer.cited_indices.length > 0 && (
            <div className="mt-3 flex flex-wrap items-center gap-1.5 text-xs text-ink-400">
              <span className="text-[11px] uppercase tracking-wider text-ink-500">grounded in</span>
              {answer.cited_indices.map((n) => (
                <a
                  key={n}
                  href={`#evidence-${n}`}
                  className="inline-flex items-center rounded-md border border-brand-400/30 bg-brand-500/10 px-1.5 py-0.5 font-mono text-[11px] font-semibold text-brand-200 transition hover:border-brand-300/60 hover:bg-brand-500/20 hover:text-brand-100"
                >
                  [{n}]
                </a>
              ))}
              {answer.elapsed_seconds > 0 && (
                <span className="ml-1 font-mono text-[10px] text-ink-500">
                  {answer.elapsed_seconds.toFixed(2)}s
                </span>
              )}
            </div>
          )}
        </div>

        <div className="hidden flex-none flex-col items-end gap-2 md:flex">
          <Pill icon={<ShieldCheckIcon className="h-3.5 w-3.5" />}>
            <span className={result.safety.blocked_pre || result.safety.blocked_post ? "text-accent-red" : "text-accent-green"}>
              {result.safety.blocked_pre || result.safety.blocked_post ? "blocked" : "safety: clean"}
            </span>
          </Pill>
          <Pill icon={<CpuChipIcon className="h-3.5 w-3.5" />}>
            <span className="text-ink-400">judge</span>
            <span className="ml-1 font-medium text-ink-100">{adapterShort}</span>
          </Pill>
        </div>
      </div>
    </motion.section>
  );
}

/** Render the answer text with inline highlighted [n] citation chips. */
function AnswerText({ text }: { text: string }) {
  const parts = text.split(/(\[\d{1,2}\])/g);
  return (
    <>
      {parts.map((part, i) => {
        const m = part.match(/^\[(\d{1,2})\]$/);
        if (m) {
          const n = Number(m[1]);
          return (
            <a
              key={i}
              href={`#evidence-${n}`}
              className="mx-0.5 inline-flex items-center rounded-md border border-brand-400/30 bg-brand-500/10 px-1 py-0 align-baseline font-mono text-[11px] font-semibold text-brand-200 transition hover:border-brand-300/60 hover:bg-brand-500/20 hover:text-brand-100"
            >
              [{n}]
            </a>
          );
        }
        return <span key={i}>{part}</span>;
      })}
    </>
  );
}

function Pill({ icon, children }: { icon: React.ReactNode; children: React.ReactNode }) {
  return (
    <span className="inline-flex items-center gap-1.5 rounded-full border border-white/10 bg-white/[0.04] px-3 py-1 text-xs text-ink-200 backdrop-blur">
      {icon}
      {children}
    </span>
  );
}
