"use client";

import { AnimatePresence, motion } from "framer-motion";
import {
  ClockIcon,
  CpuChipIcon,
  DocumentTextIcon,
  ExclamationTriangleIcon,
  MagnifyingGlassCircleIcon,
  ShieldCheckIcon,
  SparklesIcon,
  XMarkIcon,
} from "@heroicons/react/24/outline";
import { useCallback, useEffect, useState } from "react";
import { createPortal } from "react-dom";

import type { EvidenceItem, ResearchResponse } from "@/lib/types";

interface ResearchReportProps {
  result: ResearchResponse;
  v3Supported: number;
  v3Total: number;
  safetyClean: boolean;
}

/**
 * Integrated "Research Report" card.
 *
 * Replaces the floating stat-pill bar + AnswerHero combo with one
 * cohesive surface:
 *   - report header   (label + locally-generated chip + metric pills)
 *   - question block
 *   - 2-column body  (answer text on the left, verification sidebar on the right)
 *
 * Inline [n] citation chips are preserved, as is the fallback path when
 * the local LLM didn't produce a generated answer.
 */
export function ResearchReport({
  result,
  v3Supported,
  v3Total,
  safetyClean,
}: ResearchReportProps) {
  const decision = result.output.decision;
  const answer = result.answer ?? null;
  const fallbackSynthesis =
    decision?.synthesis ?? "Pipeline completed but produced no synthesis.";
  const showFallback = !answer || !answer.generated || !answer.text;
  const answerText = showFallback ? fallbackSynthesis : answer!.text;

  const adapter =
    (result.adapter_metadata?.["sft_adapter"] as string | undefined) ??
    (result.adapter_metadata?.["adapter_path"] as string | undefined) ??
    "v3";
  const adapterShort = adapter.split("/").pop() ?? adapter;

  const evidenceCount = result.output.evidence.length;
  const claimCount = decision?.claims.length ?? 0;

  // ── Retrieval-quality signal ───────────────────────────────────────────
  // Quietly inspect the evidence relevance scores.  If the top passages
  // don't actually match the question well, surface that fact — otherwise
  // a confidently-cited answer can hide a retrieval miss (e.g. a BRCA1
  // question answered with colorectal-cancer passages because they were
  // the closest matches in the local SciFact corpus).
  const relevances = result.output.evidence.map((e) => e.relevance);
  const meanRel =
    relevances.length === 0
      ? 0
      : relevances.reduce((acc, r) => acc + r, 0) / relevances.length;
  const maxRel = relevances.length === 0 ? 0 : Math.max(...relevances);
  const lowRelevance =
    relevances.length > 0 && (meanRel < 0.4 || maxRel < 0.55);

  // ── Citation modal state ─────────────────────────────────────────────────
  // 1-indexed citation number that's currently open in the modal, or
  // null when the modal is closed.  Hover tooltips overlapped the
  // floating command bar and the workspace tabs; a centered modal
  // sidesteps every stacking edge case.
  const [openCite, setOpenCite] = useState<number | null>(null);
  const handleOpenCite = useCallback((n: number) => setOpenCite(n), []);
  const handleCloseCite = useCallback(() => setOpenCite(null), []);

  return (
    <motion.section
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, ease: "easeOut" }}
      className="surface-panel relative rounded-3xl"
    >
      {/* Hero atmosphere — clipped to the card so the corner glow doesn't
          leak, but kept in its own layer so citation hover-cards can
          escape the section bounds. */}
      <div className="pointer-events-none absolute inset-0 overflow-hidden rounded-3xl">
        <div className="absolute inset-0 bg-hero-gradient opacity-90" />
        <div className="absolute -top-24 left-1/2 h-48 w-[40rem] -translate-x-1/2 rounded-full bg-brand-500/25 blur-3xl" />
      </div>
      <div className="pointer-events-none absolute inset-0 rounded-3xl ring-1 ring-inset ring-white/[0.06]" />

      {/* ───── Report header ───── */}
      <header className="relative flex flex-wrap items-center justify-between gap-x-6 gap-y-3 border-b border-white/[0.06] px-6 pt-5 pb-4 md:px-9">
        <div className="flex items-center gap-2.5">
          <SparklesIcon className="h-4 w-4 text-brand-300" />
          <h2 className="text-[11px] font-semibold uppercase tracking-[0.22em] text-ink-100">
            Research report
          </h2>
          {answer?.generated ? (
            <span
              title="Generated by the base Qwen-0.5B-Instruct model. The v3 LoRA adapter judges each claim pairwise."
              className="inline-flex items-center gap-1 rounded-full border border-brand-400/30 bg-brand-500/10 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider text-brand-200"
            >
              generated locally
            </span>
          ) : (
            <span className="inline-flex items-center gap-1 rounded-full border border-accent-amber/30 bg-accent-amber/10 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider text-accent-amber">
              fallback
            </span>
          )}
        </div>

        <div className="flex flex-wrap items-center gap-1.5">
          <MetricPill
            icon={<DocumentTextIcon className="h-3.5 w-3.5" />}
            value={evidenceCount}
            label="passages"
            tone="brand"
          />
          <MetricPill
            icon={<SparklesIcon className="h-3.5 w-3.5" />}
            value={claimCount}
            label="claims"
            tone="violet"
          />
          <MetricPill
            icon={<CpuChipIcon className="h-3.5 w-3.5" />}
            value={v3Total === 0 ? "…" : `${v3Supported}/${v3Total}`}
            label="supported"
            tone={
              v3Total === 0
                ? "muted"
                : v3Supported === v3Total
                ? "green"
                : v3Supported >= v3Total / 2
                ? "brand"
                : "amber"
            }
            title="Fraction of extracted claims the fine-tuned v3 adapter judged supported in a pairwise A/B vote."
          />
          <MetricPill
            icon={<ShieldCheckIcon className="h-3.5 w-3.5" />}
            value={safetyClean ? "clean" : "blocked"}
            label="safety"
            tone={safetyClean ? "green" : "red"}
          />
          <MetricPill
            icon={<ClockIcon className="h-3.5 w-3.5" />}
            value={`${result.elapsed_seconds.toFixed(1)}s`}
            label="end-to-end"
            tone="muted"
          />
        </div>
      </header>

      {/* ───── Question + body ───── */}
      <div className="relative px-6 pt-6 pb-7 md:px-9 md:pt-7 md:pb-9">
        <div className="text-[11px] font-semibold uppercase tracking-[0.18em] text-brand-300">
          Question
        </div>
        <h3 className="mt-1.5 text-lg font-semibold leading-snug text-ink-50 md:text-[22px]">
          {result.goal}
        </h3>

        <div className="mt-6 grid gap-6 md:grid-cols-[minmax(0,1fr)_240px] md:gap-8">
          {/* Main answer column */}
          <div className="min-w-0">
            <div className="mb-2 flex items-center gap-2">
              <div className="text-[11px] font-semibold uppercase tracking-[0.18em] text-brand-300">
                Answer
              </div>
              {!answer?.generated && (
                <span className="inline-flex items-center gap-1 rounded-full border border-accent-amber/30 bg-accent-amber/10 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider text-accent-amber">
                  <ExclamationTriangleIcon className="h-3 w-3" />
                  fallback synthesis
                </span>
              )}
            </div>

            {/* Low-relevance retrieval warning — only shown when the top
                passages don't appear to actually match the question.
                Avoids the failure mode where the UI looks confident
                ("2/2 supported") even though retrieval was off-topic. */}
            {lowRelevance && (
              <div className="mb-3 flex items-start gap-2.5 rounded-xl border border-accent-amber/30 bg-accent-amber/[0.06] px-3.5 py-3">
                <ExclamationTriangleIcon className="mt-0.5 h-4 w-4 flex-none text-accent-amber" />
                <div className="min-w-0">
                  <div className="text-[11px] font-semibold uppercase tracking-[0.18em] text-accent-amber">
                    Low retrieval relevance
                  </div>
                  <p className="mt-0.5 text-[12.5px] leading-snug text-ink-200">
                    The top passages may not match your question closely — mean{" "}
                    <span className="font-mono text-ink-100">
                      {Math.round(meanRel * 100)}%
                    </span>
                    , max{" "}
                    <span className="font-mono text-ink-100">
                      {Math.round(maxRel * 100)}%
                    </span>
                    . The answer below is faithfully grounded in what was retrieved,
                    but it could be off-topic. Try rephrasing the question, or open the{" "}
                    <span className="font-semibold text-ink-100">Evidence</span> tab to
                    inspect what the retriever actually pulled.
                  </p>
                </div>
              </div>
            )}

            <p className="text-[15px] leading-relaxed text-ink-100 md:text-[17px] md:leading-[1.7]">
              <AnswerText
                text={answerText}
                evidence={result.output.evidence}
                onOpenCite={handleOpenCite}
              />
            </p>

            {answer?.generated && answer.cited_indices.length > 0 && (
              <div className="mt-4 flex flex-wrap items-center gap-1.5 text-xs text-ink-400">
                <span className="text-[11px] uppercase tracking-wider text-ink-500">
                  grounded in
                </span>
                {answer.cited_indices.map((n) => (
                  <CitationChip
                    key={n}
                    n={n}
                    ev={result.output.evidence[n - 1]}
                    variant="footer"
                    onOpen={handleOpenCite}
                  />
                ))}
                {answer.elapsed_seconds > 0 && (
                  <span className="ml-1 font-mono text-[10px] text-ink-500">
                    {answer.elapsed_seconds.toFixed(2)}s
                  </span>
                )}
              </div>
            )}

            {/* Known unknowns — honest "what we couldn't answer" panel.
                Only renders when the decision packet actually flagged
                information gaps; empty arrays stay invisible. */}
            {decision &&
              decision.information_gaps &&
              decision.information_gaps.length > 0 && (
                <KnownUnknowns gaps={decision.information_gaps} />
              )}
          </div>

          {/* Verification sidebar */}
          <aside className="md:border-l md:border-white/[0.06] md:pl-6">
            <div className="mb-3 text-[10.5px] font-semibold uppercase tracking-[0.22em] text-ink-400">
              Verification
            </div>

            <SidebarRow
              icon={<ShieldCheckIcon className="h-3.5 w-3.5" />}
              label="safety"
              tone={safetyClean ? "green" : "red"}
              value={safetyClean ? "clean" : "blocked"}
            />
            <SidebarRow
              icon={<CpuChipIcon className="h-3.5 w-3.5" />}
              label="judge"
              value={adapterShort}
              valueClass="font-mono text-[11px] text-ink-100"
              title="Fine-tuned LoRA adapter used for pairwise claim judging."
            />
            <SidebarRow
              icon={<SparklesIcon className="h-3.5 w-3.5" />}
              label="support"
              tone={
                v3Total === 0
                  ? "muted"
                  : v3Supported === v3Total
                  ? "green"
                  : v3Supported >= v3Total / 2
                  ? "brand"
                  : "amber"
              }
              value={v3Total === 0 ? "judging…" : `${v3Supported}/${v3Total}`}
            />
            <SidebarRow
              icon={<DocumentTextIcon className="h-3.5 w-3.5" />}
              label="evidence"
              value={`${evidenceCount} passage${evidenceCount === 1 ? "" : "s"}`}
            />
            <SidebarRow
              icon={<ClockIcon className="h-3.5 w-3.5" />}
              label="runtime"
              value={`${result.elapsed_seconds.toFixed(1)}s`}
              valueClass="font-mono text-[12px] text-ink-100"
            />

            {/* Tiny pipeline summary — full timeline available in workspace below */}
            <div className="mt-4 rounded-lg border border-white/[0.06] bg-white/[0.02] p-2.5">
              <div className="mb-1 text-[9.5px] font-semibold uppercase tracking-[0.18em] text-ink-500">
                Pipeline
              </div>
              <div className="text-[10.5px] leading-snug text-ink-300">
                Plan{" "}
                <span className="text-ink-500">→</span> Retrieve{" "}
                <span className="text-ink-500">→</span> Memory{" "}
                <span className="text-ink-500">→</span> Synthesize{" "}
                <span className="text-ink-500">→</span> Verify{" "}
                <span className="text-ink-500">→</span> Judge
              </div>
            </div>
          </aside>
        </div>
      </div>

      {/* Citation modal — portal-style overlay rendered at the section
          root so it sits above the report card, the workspace tabs, and
          the floating command bar.  Closes on Esc, backdrop click, or
          the explicit close button. */}
      <CitationModal
        n={openCite}
        ev={openCite ? result.output.evidence[openCite - 1] : undefined}
        onClose={handleCloseCite}
      />
    </motion.section>
  );
}

/* ───────────────────────── helpers ───────────────────────── */

type Tone = "brand" | "violet" | "green" | "amber" | "red" | "muted";

function MetricPill({
  icon,
  value,
  label,
  tone,
  title,
}: {
  icon: React.ReactNode;
  value: React.ReactNode;
  label: string;
  tone: Tone;
  title?: string;
}) {
  const valueColor: Record<Tone, string> = {
    brand: "text-brand-200",
    violet: "text-accent-violet",
    green: "text-accent-green",
    amber: "text-accent-amber",
    red: "text-accent-red",
    muted: "text-ink-200",
  };
  const iconColor: Record<Tone, string> = {
    brand: "text-brand-300",
    violet: "text-accent-violet/90",
    green: "text-accent-green",
    amber: "text-accent-amber",
    red: "text-accent-red",
    muted: "text-ink-400",
  };
  return (
    <span
      title={title}
      className="inline-flex items-center gap-1.5 whitespace-nowrap rounded-full border border-white/10 bg-white/[0.04] px-2.5 py-1 text-xs text-ink-200 shadow-[inset_0_1px_0_rgba(255,255,255,0.05)] backdrop-blur"
    >
      <span className={iconColor[tone]}>{icon}</span>
      <span className={`font-mono text-[12px] font-semibold ${valueColor[tone]}`}>
        {value}
      </span>
      <span className="text-[10px] uppercase tracking-[0.14em] text-ink-500">
        {label}
      </span>
    </span>
  );
}

function SidebarRow({
  icon,
  label,
  value,
  tone,
  valueClass,
  title,
}: {
  icon: React.ReactNode;
  label: string;
  value: React.ReactNode;
  tone?: Tone;
  valueClass?: string;
  title?: string;
}) {
  const valueColor: Record<Tone, string> = {
    brand: "text-brand-200",
    violet: "text-accent-violet",
    green: "text-accent-green",
    amber: "text-accent-amber",
    red: "text-accent-red",
    muted: "text-ink-200",
  };
  const computed =
    valueClass ?? `text-[12px] font-semibold ${tone ? valueColor[tone] : "text-ink-100"}`;
  return (
    <div
      title={title}
      className="flex items-center justify-between gap-3 border-b border-white/[0.04] py-2 last:border-b-0"
    >
      <div className="flex items-center gap-1.5 text-[11px] uppercase tracking-[0.14em] text-ink-500">
        <span className="text-ink-400">{icon}</span>
        {label}
      </div>
      <div className={computed}>{value}</div>
    </div>
  );
}

/** Inline-highlight `[n]` citation chips inside the answer prose. */
function AnswerText({
  text,
  evidence,
  onOpenCite,
}: {
  text: string;
  evidence: EvidenceItem[];
  onOpenCite: (n: number) => void;
}) {
  const parts = text.split(/(\[\d{1,2}\])/g);
  return (
    <>
      {parts.map((part, i) => {
        const m = part.match(/^\[(\d{1,2})\]$/);
        if (m) {
          const n = Number(m[1]);
          return (
            <CitationChip
              key={i}
              n={n}
              ev={evidence[n - 1]}
              variant="inline"
              onOpen={onOpenCite}
            />
          );
        }
        return <span key={i}>{part}</span>;
      })}
    </>
  );
}

/**
 * Citation chip.  Click opens the centered citation modal with the
 * full passage; out-of-range citations (model emits [9] with only 3
 * passages) gracefully degrade to a no-op chip.
 */
function CitationChip({
  n,
  ev,
  variant,
  onOpen,
}: {
  n: number;
  ev: EvidenceItem | undefined;
  variant: "inline" | "footer";
  onOpen: (n: number) => void;
}) {
  const chipClass =
    variant === "footer"
      ? "inline-flex items-center rounded-md border border-brand-400/30 bg-brand-500/10 px-1.5 py-0.5 font-mono text-[11px] font-semibold text-brand-200 transition hover:border-brand-300/60 hover:bg-brand-500/20 hover:text-brand-100"
      : "mx-0.5 inline-flex items-center rounded-md border border-brand-400/30 bg-brand-500/10 px-1 py-0 align-baseline font-mono text-[11px] font-semibold text-brand-200 transition hover:border-brand-300/60 hover:bg-brand-500/20 hover:text-brand-100";

  if (!ev) {
    return (
      <span className={chipClass} title="Cited passage is out of range">
        [{n}]
      </span>
    );
  }

  return (
    <button
      type="button"
      onClick={() => onOpen(n)}
      className={`${chipClass} cursor-pointer`}
      aria-label={`Open passage ${n}`}
    >
      [{n}]
    </button>
  );
}

/**
 * Centered citation modal.  Renders the full source title and passage
 * content for a cited passage, plus relevance, evidence_id, and a
 * "jump to evidence row" link.  Dismissed via Esc, backdrop click, or
 * the explicit close button.  Locks body scroll while open.
 */
function CitationModal({
  n,
  ev,
  onClose,
}: {
  n: number | null;
  ev: EvidenceItem | undefined;
  onClose: () => void;
}) {
  const isOpen = n !== null && ev !== undefined;
  const [mounted, setMounted] = useState(false);

  // SSR safety: only access document on the client.
  useEffect(() => setMounted(true), []);

  // Esc-to-close + body-scroll lock.  Listener is only attached while
  // the modal is mounted so it doesn't interfere with other key flows
  // (e.g. textarea editing) when closed.
  useEffect(() => {
    if (!isOpen) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
    };
    window.addEventListener("keydown", onKey);
    const prevOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    return () => {
      window.removeEventListener("keydown", onKey);
      document.body.style.overflow = prevOverflow;
    };
  }, [isOpen, onClose]);

  if (!mounted) return null;

  // Portal to document.body so the modal escapes any ancestor `transform`
  // (notably framer-motion's animated parent), which would otherwise turn
  // `position: fixed` into a *containing-block-relative* position and let
  // the command bar bleed through above the backdrop.
  return createPortal(
    <AnimatePresence>
      {isOpen && ev && n !== null && (
        <motion.div
          className="fixed inset-0 z-[100] flex items-center justify-center p-4 sm:p-6"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.18, ease: "easeOut" }}
          role="dialog"
          aria-modal="true"
          aria-labelledby={`citation-modal-title-${n}`}
        >
          {/* Backdrop — deep obsidian + blur so the modal is unambiguously
              the foreground.  Click anywhere outside the card to close. */}
          <button
            type="button"
            aria-label="Close passage"
            onClick={onClose}
            className="absolute inset-0 bg-[#020617]/90 backdrop-blur-md"
          />

          {/* Modal card */}
          <motion.div
            initial={{ opacity: 0, scale: 0.97, y: 6 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.98, y: 4 }}
            transition={{ duration: 0.22, ease: [0.22, 1, 0.36, 1] }}
            className="relative z-10 w-full max-w-xl overflow-hidden rounded-2xl border border-white/[0.08] bg-[#0a1120] shadow-[0_30px_80px_-20px_rgba(0,0,0,0.85)]"
          >
            <CitationModalBody n={n} ev={ev} onClose={onClose} />
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>,
    document.body,
  );
}

function CitationModalBody({
  n,
  ev,
  onClose,
}: {
  n: number;
  ev: EvidenceItem;
  onClose: () => void;
}) {
  const relPct = Math.round(ev.relevance * 100);
  const relTone =
    relPct >= 70
      ? "text-accent-green"
      : relPct >= 50
      ? "text-brand-200"
      : "text-accent-amber";
  const relBar =
    relPct >= 70
      ? "from-accent-green to-emerald-400"
      : relPct >= 50
      ? "from-brand-500 to-accent-cyan"
      : "from-accent-amber to-orange-400";
  const additional = ev.source.additional as Record<string, unknown> | undefined;
  const docIdRaw = additional?.["doc_id"];
  const docId =
    typeof docIdRaw === "string" || typeof docIdRaw === "number"
      ? String(docIdRaw)
      : null;

  return (
    <>
      {/* Header ─ minimal: chip + title + close. */}
      <header className="flex items-start justify-between gap-4 border-b border-white/[0.05] px-6 pt-5 pb-4">
        <div className="min-w-0">
          <div className="flex items-center gap-2">
            <span className="inline-flex items-center gap-1 rounded-md border border-brand-400/30 bg-brand-500/10 px-1.5 py-0.5 font-mono text-[10.5px] font-semibold text-brand-200">
              <DocumentTextIcon className="h-3 w-3" />[{n}]
            </span>
            <span className="text-[10px] uppercase tracking-[0.18em] text-ink-500">
              cited source
            </span>
          </div>
          {ev.source.title && (
            <h3
              id={`citation-modal-title-${n}`}
              className="mt-2.5 text-[15px] font-semibold leading-snug text-ink-50"
            >
              {ev.source.title}
            </h3>
          )}
        </div>
        <button
          type="button"
          onClick={onClose}
          className="flex-none rounded-md p-1.5 text-ink-500 transition hover:bg-white/[0.05] hover:text-ink-100"
          aria-label="Close"
        >
          <XMarkIcon className="h-4 w-4" />
        </button>
      </header>

      {/* Relevance strip ─ thin bar, label + value on one line. */}
      <div className="flex items-center gap-3 border-b border-white/[0.05] px-6 py-3">
        <span className="text-[10px] font-semibold uppercase tracking-[0.16em] text-ink-500">
          Relevance
        </span>
        <div className="h-1 flex-1 overflow-hidden rounded-full bg-white/[0.05]">
          <motion.div
            initial={{ width: 0 }}
            animate={{ width: `${relPct}%` }}
            transition={{ duration: 0.5, ease: "easeOut", delay: 0.08 }}
            className={`h-full rounded-full bg-gradient-to-r ${relBar}`}
          />
        </div>
        <span className={`font-mono text-[11px] font-semibold ${relTone}`}>
          {relPct}%
        </span>
      </div>

      {/* Body ─ the passage, generously padded and scrollable. */}
      <div className="max-h-[55vh] overflow-y-auto px-6 py-5">
        <p className="whitespace-pre-wrap text-[14px] leading-[1.7] text-ink-100">
          {ev.content}
        </p>
      </div>

      {/* Footer ─ source meta + jump link. */}
      <footer className="flex flex-wrap items-center justify-between gap-3 border-t border-white/[0.05] px-6 py-3 text-[11px]">
        <span
          title={ev.evidence_id}
          className="truncate font-mono text-[10.5px] text-ink-500"
        >
          {ev.evidence_id}
          {docId && (
            <span className="ml-2 text-ink-600">· S2 CorpusID {docId}</span>
          )}
        </span>
        <a
          href={`#evidence-${n}`}
          onClick={onClose}
          className="inline-flex flex-none items-center gap-1 text-[11.5px] font-semibold text-brand-300 transition hover:text-brand-200"
        >
          jump to evidence row
          <span aria-hidden>→</span>
        </a>
      </footer>
    </>
  );
}

/**
 * "Known unknowns" — surfaces the information gaps that the synthesizer
 * couldn't resolve from the retrieved evidence.  This is a non-negotiable
 * honesty signal: a confident-looking answer with hidden gaps is worse
 * than a confident-looking answer with the gaps named out loud.
 */
function KnownUnknowns({ gaps }: { gaps: string[] }) {
  // Deduplicate + drop empties.  The synthesizer sometimes emits a
  // bullet that is just whitespace or a repeat of the goal; filter
  // those out so we don't render "•" placeholders.
  const seen = new Set<string>();
  const items = gaps
    .map((g) => g.trim())
    .filter((g) => {
      if (!g) return false;
      const key = g.toLowerCase();
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    });
  if (items.length === 0) return null;

  return (
    <div className="mt-6 rounded-xl border border-accent-amber/25 bg-accent-amber/[0.04] p-4">
      <div className="flex items-center gap-2">
        <MagnifyingGlassCircleIcon className="h-4 w-4 text-accent-amber" />
        <h4 className="text-[11px] font-semibold uppercase tracking-[0.18em] text-accent-amber">
          Known unknowns
        </h4>
        <span className="rounded-full bg-accent-amber/15 px-1.5 py-0.5 font-mono text-[10px] font-semibold text-accent-amber">
          {items.length}
        </span>
      </div>
      <p className="mt-1 text-[11.5px] leading-snug text-ink-400">
        Gaps the synthesizer flagged from the retrieved evidence — not answered
        above and worth a follow-up query.
      </p>
      <ul className="mt-2.5 space-y-1.5">
        {items.map((gap, idx) => (
          <li
            key={idx}
            className="flex items-start gap-2 text-[12.5px] leading-snug text-ink-200"
          >
            <span className="mt-1.5 h-1 w-1 flex-none rounded-full bg-accent-amber" />
            <span>{gap}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}
